// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI_VR3g8eF5mdma2-9uTDPveM72FgNydc',
    appId: '1:760693087937:web:57da720514d4d07a063e40',
    messagingSenderId: '760693087937',
    projectId: 'leaf-56423',
    authDomain: 'leaf-56423.firebaseapp.com',
    storageBucket: 'leaf-56423.firebasestorage.app',
    measurementId: 'G-SWT8MNDQ78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI5M3iMD58cBSL6RIQahPYpOIpdgd_ArU',
    appId: '1:760693087937:android:000b9bbacf03c741063e40',
    messagingSenderId: '760693087937',
    projectId: 'leaf-56423',
    storageBucket: 'leaf-56423.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp0eSuvyKz_u0zjV9plvXcIIEAq4002Mk',
    appId: '1:760693087937:ios:2a744fca0395d028063e40',
    messagingSenderId: '760693087937',
    projectId: 'leaf-56423',
    storageBucket: 'leaf-56423.firebasestorage.app',
    iosBundleId: 'com.example.leaf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp0eSuvyKz_u0zjV9plvXcIIEAq4002Mk',
    appId: '1:760693087937:ios:2a744fca0395d028063e40',
    messagingSenderId: '760693087937',
    projectId: 'leaf-56423',
    storageBucket: 'leaf-56423.firebasestorage.app',
    iosBundleId: 'com.example.leaf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCI_VR3g8eF5mdma2-9uTDPveM72FgNydc',
    appId: '1:760693087937:web:bfff558d71fd11ea063e40',
    messagingSenderId: '760693087937',
    projectId: 'leaf-56423',
    authDomain: 'leaf-56423.firebaseapp.com',
    storageBucket: 'leaf-56423.firebasestorage.app',
    measurementId: 'G-1EVBTTWFC0',
  );
}